baseurl: /daily
port: 4040
destination: ./_trial
github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
collections:
  lessons:
    output: true
  pages:
    output: true
include: ['.htaccess']
exclude: [not-in-git, node_modules, gulpfile.js,  artwork, csv_to_html]
trialdeploy: true

texts:
  vn:
    upgrade_url: https://get.englishletics.com/vi/?add-to-cart=71&chatfuelid=MYCHATFUELID
    salespage_url: https://get.englishletics.com/vi/nguoi-su-dung-phien-ban-cao-cap-hoc-tieng-anh-nhanh-va-hieu-qua-hon/?chatfuelid=MYCHATFUELID
    help_url: https://get.englishletics.com/vi/giup/?chatfuelid=MYCHATFUELID
  pt:
    upgrade_url: https://get.englishletics.com/pt-br/?add-to-cart=70&chatfuelid=MYCHATFUELID
    salespage_url: https://get.englishletics.com/pt-br/as-pessoas-em-versao-premium-aprendem-o-ingles-mais-rapido-e-melhor/?chatfuelid=MYCHATFUELID
    help_url: https://get.englishletics.com/pt-br/ajuda/?chatfuelid=MYCHATFUELID
  en:
    upgrade_url: https://get.englishletics.com/en/?add-to-cart=8&chatfuelid=MYCHATFUELID
    salespage_url: https://get.englishletics.com/en/people-going-premium-learn-english-faster-and-better/?chatfuelid=MYCHATFUELID
    help_url: https://get.englishletics.com/en/help/?chatfuelid=MYCHATFUELID
